/**
 * @file    main.h
 * @brief   MSPM0G3507 24diansai — Master header with pin definitions
 *
 * @note    This file replaces the STM32F1 HAL main.h.  All HAL references
 *          (stm32f1xx_hal.h) are removed; TI DriverLib headers are included
 *          via ti_msp_dl_config.h.
 *
 * Pin assignments are based on the TianMengXing MSPM0G3507 board.
 * Adjust to match your actual wiring.
 */
#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/* DriverLib includes (generated by SysConfig or hand-written)        */
/* ------------------------------------------------------------------ */
#include "ti_msp_dl_config.h"

/* ------------------------------------------------------------------ */
/* Standard headers                                                   */
/* ------------------------------------------------------------------ */
#include <stdint.h>
#include <stdbool.h>

/* ================================================================== */
/*  Pin definitions — adjust to match your actual board wiring!       */
/* ================================================================== */

/* ---------- Motor PWM (TIMA0, edge-aligned, ~10 kHz) ---------- */
#define PWM_L_PORT              GPIOA
#define PWM_L_PIN               DL_GPIO_PIN_7          /* PA7 = TIMA0_CH0 */
#define PWM_L_IOMUX             TIMA0_CH0_IOMUX

#define PWM_R_PORT              GPIOA
#define PWM_R_PIN               DL_GPIO_PIN_12         /* PA12 = TIMA0_CH2 (or PA6=TIMA0_CH1 if HFX unused) */
#define PWM_R_IOMUX             TIMA0_CH2_IOMUX

#define PWM_PERIOD_TICKS        7999                    /* 80 MHz / 8000 = 10 kHz */
#define PWM_MAX_DUTY            PWM_PERIOD_TICKS

/* ---------- Motor direction (plain GPIO push-pull) ---------- */
#define IN1_PORT                GPIOB
#define IN1_PIN                 DL_GPIO_PIN_0           /* PB0 = IN1 (左轮正转) */
#define IN1_IOMUX               GPIOB_IOMUX_PB0

#define IN2_PORT                GPIOB
#define IN2_PIN                 DL_GPIO_PIN_1           /* PB1 = IN2 (左轮反转) */
#define IN2_IOMUX               GPIOB_IOMUX_PB1

#define IN3_PORT                GPIOB
#define IN3_PIN                 DL_GPIO_PIN_2           /* PB2 = IN3 (右轮正转) */
#define IN3_IOMUX               GPIOB_IOMUX_PB2

#define IN4_PORT                GPIOB
#define IN4_PIN                 DL_GPIO_PIN_3           /* PB3 = IN4 (右轮反转) */
#define IN4_IOMUX               GPIOB_IOMUX_PB3

/* ---------- Encoder QEI (TIMG0 = left, TIMG1 = right) ---------- */
#define ENC_L_TIMG              TIMG0
#define ENC_L_CHA_PORT          GPIOB
#define ENC_L_CHA_PIN           DL_GPIO_PIN_6           /* PB6 = TIMG0_CH0 */
#define ENC_L_CHA_IOMUX         TIMG0_CH0_IOMUX
#define ENC_L_CHB_PIN           DL_GPIO_PIN_7           /* PB7 = TIMG0_CH1 */
#define ENC_L_CHB_IOMUX         TIMG0_CH1_IOMUX

#define ENC_R_TIMG              TIMG1
#define ENC_R_CHA_PORT          GPIOA
#define ENC_R_CHA_PIN           DL_GPIO_PIN_14          /* PA14 = TIMG1_CH0 */
#define ENC_R_CHA_IOMUX         TIMG1_CH0_IOMUX
#define ENC_R_CHB_PORT          GPIOA
#define ENC_R_CHB_PIN           DL_GPIO_PIN_15          /* PA15 = TIMG1_CH1 */
#define ENC_R_CHB_IOMUX         TIMG1_CH1_IOMUX

#define ENC_PERIOD              65535U

/* ---------- Track sensors D1-D7 (input pull-up, active-high = on line) ---------- */
#define TRACK_PORT              GPIOA
#define TRACK_D1_PIN            DL_GPIO_PIN_0           /* PA0 */
#define TRACK_D2_PIN            DL_GPIO_PIN_1           /* PA1 */
#define TRACK_D3_PIN            DL_GPIO_PIN_14          /* PA14 */
#define TRACK_D4_PIN            DL_GPIO_PIN_15          /* PA15 */
#define TRACK_D5_PIN            DL_GPIO_PIN_16          /* PA16 */
#define TRACK_D6_PIN            DL_GPIO_PIN_17          /* PA17 */
#define TRACK_D7_PIN            DL_GPIO_PIN_27          /* PA27 */

#define TRACK_ALL_MASK          (DL_GPIO_PIN_0  | DL_GPIO_PIN_1  | \
                                 DL_GPIO_PIN_14 | DL_GPIO_PIN_15 | \
                                 DL_GPIO_PIN_16 | DL_GPIO_PIN_17 | \
                                 DL_GPIO_PIN_27)

/* ---------- Buttons (input pull-up, active-low) ---------- */
#define BUTTON_PORT             GPIOB
#define BUTTON1_PIN             DL_GPIO_PIN_8           /* PB8  → Task Q1 */
#define BUTTON2_PIN             DL_GPIO_PIN_9           /* PB9  → Task Q2 */
#define BUTTON3_PIN             DL_GPIO_PIN_10          /* PB10 → Task Q3 */
#define BUTTON4_PIN             DL_GPIO_PIN_11          /* PB11 → Task Q4 */

#define BUTTON_ALL_MASK         (DL_GPIO_PIN_8  | DL_GPIO_PIN_9  | \
                                 DL_GPIO_PIN_10 | DL_GPIO_PIN_11)

/* ---------- LED & Buzzer (push-pull output) ---------- */
#define LED_PORT                GPIOB
#define LED_PIN                 DL_GPIO_PIN_12          /* PB12, active-high = ON */
#define LED_IOMUX               GPIOB_IOMUX_PB12

#define BUZZER_PORT             GPIOB
#define BUZZER_PIN              DL_GPIO_PIN_13          /* PB13, active-low = ON */
#define BUZZER_IOMUX            GPIOB_IOMUX_PB13

/* ---------- UART (DriverLib instances) ---------- */
/* UART0 = debug printf (PA10 TX / PA11 RX, shares CH340E USB-serial) */
#define DEBUG_UART              UART0
#define DEBUG_UART_INT          UART0_IRQn
#define DEBUG_TX_PORT           GPIOA
#define DEBUG_TX_PIN            DL_GPIO_PIN_10
#define DEBUG_TX_IOMUX          UART0_TX_IOMUX
#define DEBUG_RX_PORT           GPIOA
#define DEBUG_RX_PIN            DL_GPIO_PIN_11
#define DEBUG_RX_IOMUX          UART0_RX_IOMUX

/* UART1 = JY61P IMU (PA8 TX / PA9 RX) */
#define IMU_UART                UART1
#define IMU_UART_INT            UART1_IRQn
#define IMU_TX_PORT             GPIOA
#define IMU_TX_PIN              DL_GPIO_PIN_8
#define IMU_TX_IOMUX            UART1_TX_IOMUX
#define IMU_RX_PORT             GPIOA
#define IMU_RX_PIN              DL_GPIO_PIN_9
#define IMU_RX_IOMUX            UART1_RX_IOMUX

/* ---------- Control timer (25 Hz periodic interrupt) ---------- */
#define CONTROL_TIMG            TIMG2
#define CONTROL_TIMG_INT        TIMG2_IRQn
/* 80 MHz / 80 / 40000 = 25 Hz exactly */
#define CONTROL_PRESCALER       DL_TIMER_CLOCK_DIVIDE_80
#define CONTROL_PERIOD          39999U

/* ================================================================== */
/*  Common macros                                                     */
/* ================================================================== */
#define UNUSED(x)               ((void)(x))

/* ================================================================== */
/*  Exported functions                                                */
/* ================================================================== */
void Error_Handler(void);

#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H__ */
